### ISSUE TITLE
Getting the data from the circular buffer

### ISSUE THREAD

**Issue by gerazov** [vstadnytskyi/circular_buffer_numpy#2]
Kudos for the project :clap: 

This is a question/suggestion. Is there an easy way to get the data from the `CircularBuffer`?
Currently `buffer.get_all()` returns `NaN`s for memory not filled yet, so the only way I can think of doing it is by `buffer.get_all()[~np.isnan(buffer.get_all())]`. This is a bit verbose and having a `get_data()` convenience function would make things easier :+1:

**Comment by vstadnytskyi** [comment]
@gerazov 

I am glad you found it useful and please feel free to submit more issue and suggestions. 

I kept vector operations(which are very fast) in mind when I was designing this library. Indeed the command `buffer.get_all()[~np.isnan(buffer.get_all())]` is verbose but also it will be slow since it will require operations on the entire buffer. 

We could consider a function that returns all "valid" values from the buffer and the name get_data sounds like a good name. So this function will return all valid values and order them so latest collected are at the end. It will work as` get_all()` and might even completely replace it with time. Frankly, I never even considered modification you proposed because the circular buffer is designed to run continuously so there are "invalid" values only for few seconds at the very beginning. I have this implementation running on software that collects data continuously for weeks and I can access last N known valid values.

**Comment by vstadnytskyi** [comment]
I have added the function and published a new version 0.0.16

**Comment by gerazov** [comment]
Thanks for the fast reply and even speedier fix @vstadnytskyi ! :clap: 

In fact we're using a 10 s long buffer so we need to handle the init period as well :slightly_smiling_face: 

btw I also tried `buffer.get_last_N(buffer.get_length())` but this also gave the whole buffer with the NaNs, so again we would have to keep track of N.

**Comment by vstadnytskyi** [comment]
@gerazov 

The function get_last_N returns last N values. Since you have specified N = buffer.get_length(), you got the full buffer. If you specify ,for example, N = 10, then you get last 10 points. I was just wondering. Did you think that "length" is number of valid entires in the buffer? I use length as the full length of the circular buffer and not how many valid entries are available. I divided the shape of the buffer into two components: length and data_shape. length is how many values can be in the buffer and data_shape is tell what is the shape of a data point. For example, I use circular buffers for interaction with cameras. I have a circular buffer with length = 64 and data_shape = 4096X3000. It allows me to keep last 64 images saved in the memory so they are ready for retrieval if needed.

I incline to leave the get_last_N as it is since it is lower lever helper function and usually is not used that often at least by me :).

**Comment by gerazov** [comment]
No no, I thought it would get the last valid data points, you don't have to change it. Maybe make it clear in the documentation that `NaN`s are returned if the buffer is still empty. I would add the some explanatory code to the documentation - this is what I used to clear things up for me :slightly_smiling_face: :

```python
buffer = CircularBuffer(shape=10)
for i in range(10):
    buffer.append(np.ones((3, 1)) * i)
    print(buffer.pointer, buffer.get_all())
    print(buffer.get_last_N(10))
    print()
    
2 [nan nan nan nan nan nan nan  0.  0.  0.]
[nan nan nan nan nan nan nan  0.  0.  0.]

5 [nan nan nan nan  0.  0.  0.  1.  1.  1.]
[nan nan nan nan  0.  0.  0.  1.  1.  1.]

8 [nan  0.  0.  0.  1.  1.  1.  2.  2.  2.]
[nan  0.  0.  0.  1.  1.  1.  2.  2.  2.]

1 [0. 1. 1. 1. 2. 2. 2. 3. 3. 3.]
[0. 1. 1. 1. 2. 2. 2. 3. 3. 3.]

4 [1. 2. 2. 2. 3. 3. 3. 4. 4. 4.]
[1. 2. 2. 2. 3. 3. 3. 4. 4. 4.]

7 [2. 3. 3. 3. 4. 4. 4. 5. 5. 5.]
[2. 3. 3. 3. 4. 4. 4. 5. 5. 5.]

0 [3. 4. 4. 4. 5. 5. 5. 6. 6. 6.]
[3. 4. 4. 4. 5. 5. 5. 6. 6. 6.]

3 [4. 5. 5. 5. 6. 6. 6. 7. 7. 7.]
[4. 5. 5. 5. 6. 6. 6. 7. 7. 7.]

6 [5. 6. 6. 6. 7. 7. 7. 8. 8. 8.]
[5. 6. 6. 6. 7. 7. 7. 8. 8. 8.]

9 [6. 7. 7. 7. 8. 8. 8. 9. 9. 9.]
[6. 7. 7. 7. 8. 8. 8. 9. 9. 9.]
```
